name: PixelHG
main: me.ghost.Main
version: 0.1
author: GhostUEP
commands:
   kit:
   admin:
   tempo:
   ffeast:
   tag:
   checkwinner:
   pit:
   mini:
   fake:
   tfake:
   exec:
   execall:
   chat:
   invsee:
   ghost:
   pixels:
   forcekit:
   cleardrops:
   togglekit:
   skit:
   pvp:
   dano:
   help:
   conta:
   tell:
   pm:
   msg:
   ignore:
   w:
   r:
   reply:
   tpall:
   feast:
   teleport:
   report:
   players:
   connect: